export const promptGenerarLista = `Genera un arreglo JSON de exactamente 100 palabras relacionadas con el tema: "[TEMA]".

Cada elemento debe tener EXACTAMENTE esta estructura con comillas dobles:
{ "palabra": "nombre", "pista": "palabra ambigua" }

Requisitos:
- La pista debe ser UNA SOLA PALABRA o máximo DOS palabras muy ambiguas
- La pista NO debe ser específica, debe aplicar a múltiples cosas
- Debe ser extremadamente difícil adivinar solo con la pista
- Formato JSON estrictamente válido, sin comentarios, sin texto adicional
- Exactamente 100 elementos

Ejemplo de salida:
[
  { "palabra": "Pikachu", "pista": "Eléctrico" },
  { "palabra": "Naruto", "pista": "Ninja" },
  { "palabra": "Goku", "pista": "Poder" }
]`;

export default function listaPredeterminada() {
    return [
        { palabra: "Perro", pista: "Leal" },
        { palabra: "Gato", pista: "Independiente" },
        { palabra: "Pizza", pista: "Redondo" },
        { palabra: "Fútbol", pista: "Once" },
        { palabra: "Guitarra", pista: "Seis" },
        { palabra: "Computadora", pista: "Digital" },
        { palabra: "Avión", pista: "Altitud" },
        { palabra: "Playa", pista: "Frontera" },
        { palabra: "Libro", pista: "Páginas" },
        { palabra: "Teléfono", pista: "Portátil" },
        { palabra: "Cine", pista: "Oscuro" },
        { palabra: "Café", pista: "Amargo" },
        { palabra: "Bicicleta", pista: "Equilibrio" },
        { palabra: "Montaña", pista: "Elevado" },
        { palabra: "Reloj", pista: "Circular" },
        { palabra: "Zapatos", pista: "Par" },
        { palabra: "Lluvia", pista: "Gotas" },
        { palabra: "Sol", pista: "Centro" },
        { palabra: "Luna", pista: "Fases" },
        { palabra: "Árbol", pista: "Anillos" },
        { palabra: "Coche", pista: "Motor" },
        { palabra: "Helado", pista: "Frío" },
        { palabra: "Música", pista: "Ondas" },
        { palabra: "Pintura", pista: "Pigmento" },
        { palabra: "Escuela", pista: "Aprendizaje" },
        { palabra: "Hospital", pista: "Urgente" },
        { palabra: "Restaurante", pista: "Servicio" },
        { palabra: "Parque", pista: "Recreo" },
        { palabra: "Río", pista: "Corriente" },
        { palabra: "Océano", pista: "Salado" },
        { palabra: "Estrella", pista: "Brillo" },
        { palabra: "Nube", pista: "Flotante" },
        { palabra: "Flor", pista: "Pétalos" },
        { palabra: "Mariposa", pista: "Metamorfosis" },
        { palabra: "Elefante", pista: "Memoria" },
        { palabra: "León", pista: "Melena" },
        { palabra: "Tigre", pista: "Rayas" },
        { palabra: "Delfín", pista: "Sonar" },
        { palabra: "Ballena", pista: "Gigante" },
        { palabra: "Tiburón", pista: "Aleta" },
        { palabra: "Serpiente", pista: "Sinuoso" },
        { palabra: "Águila", pista: "Vista" },
        { palabra: "Pingüino", pista: "Formal" },
        { palabra: "Canguro", pista: "Bolsillo" },
        { palabra: "Jirafa", pista: "Altura" },
        { palabra: "Cebra", pista: "Patrón" },
        { palabra: "Hipopótamo", pista: "Sumergido" },
        { palabra: "Cocodrilo", pista: "Lágrimas" },
        { palabra: "Oso", pista: "Sueño" },
        { palabra: "Conejo", pista: "Veloz" },
        { palabra: "Ratón", pista: "Pequeño" },
        { palabra: "Caballo", pista: "Galope" },
        { palabra: "Vaca", pista: "Rumiante" },
        { palabra: "Cerdo", pista: "Barro" },
        { palabra: "Gallina", pista: "Cacareo" },
        { palabra: "Pato", pista: "Palmado" },
        { palabra: "Pez", pista: "Branquias" },
        { palabra: "Araña", pista: "Ocho" },
        { palabra: "Hormiga", pista: "Colonia" },
        { palabra: "Abeja", pista: "Polen" },
        { palabra: "Mosca", pista: "Zumbido" },
        { palabra: "Pan", pista: "Levadura" },
        { palabra: "Queso", pista: "Curado" },
        { palabra: "Leche", pista: "Blanco" },
        { palabra: "Huevo", pista: "Frágil" },
        { palabra: "Manzana", pista: "Newton" },
        { palabra: "Naranja", pista: "Vitamina" },
        { palabra: "Plátano", pista: "Potasio" },
        { palabra: "Fresa", pista: "Semillas" },
        { palabra: "Uva", pista: "Racimo" },
        { palabra: "Sandía", pista: "Hidratante" },
        { palabra: "Melón", pista: "Golpear" },
        { palabra: "Piña", pista: "Corona" },
        { palabra: "Limón", pista: "Ácido" },
        { palabra: "Pera", pista: "Oxidación" },
        { palabra: "Durazno", pista: "Terciopelo" },
        { palabra: "Cereza", pista: "Doble" },
        { palabra: "Tomate", pista: "Debate" },
        { palabra: "Zanahoria", pista: "Visión" },
        { palabra: "Papa", pista: "Subterráneo" },
        { palabra: "Cebolla", pista: "Capas" },
        { palabra: "Lechuga", pista: "Hojas" },
        { palabra: "Brócoli", pista: "Rechazo" },
        { palabra: "Espinaca", pista: "Hierro" },
        { palabra: "Maíz", pista: "Explosión" },
        { palabra: "Arroz", pista: "Grano" },
        { palabra: "Pasta", pista: "Trigo" },
        { palabra: "Sopa", pista: "Cuchara" },
        { palabra: "Ensalada", pista: "Fresco" },
        { palabra: "Hamburguesa", pista: "Capas" },
        { palabra: "Taco", pista: "Doblado" },
        { palabra: "Sushi", pista: "Palillos" },
        { palabra: "Chocolate", pista: "Cacao" },
        { palabra: "Caramelo", pista: "Dulce" },
        { palabra: "Galleta", pista: "Crujiente" },
        { palabra: "Pastel", pista: "Celebración" },
        { palabra: "Agua", pista: "Transparente" },
        { palabra: "Jugo", pista: "Exprimido" },
        { palabra: "Refresco", pista: "Burbujas" }
    ];
}
